---
title: "VineVisR: Dependence exploration of South African Top40 companies"
resource_files:
- R/load_pkgs.R
- R/VisVineR.R
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
    vertical_layout: scroll
    theme: "spacelab"
---
```{r global, include=FALSE}

for(i in list.files("R/", full.names = T)) source(i)

{
  library(dplyr)
  library(tibble)
  library(tidyr)
  library(ggplot2)
  library(VineCopula)
  library(DT)
  library(shinythemes)
}
```

```{r functions}
load_pkg <- function(packagelist) {
  
    # Check if any package needs installation:
  PackagesNeedingInstall <- packagelist[!(packagelist %in% installed.packages()[,"Package"])]
  if(length(PackagesNeedingInstall))
  {
    cat("\nInstalling necesarry packages: ", paste0(PackagesNeedingInstall,collapse = ", "), "\n")
    install.packages(PackagesNeedingInstall, dependencies = T)
  }
  # load packages into R:
  x <- 
  suppressPackageStartupMessages(lapply(packagelist, require, character.only = TRUE, quietly = T))
}

VisVineR <-
  function(RVM,
           group,
           group.size,
           colours,
           shape = c(
             "square",
             "triangle",
             "box",
             "circle",
             "dot",
             "star",
             "ellipse",
             "database",
             "text",
             "diamond"
           )[1],
           nodesIdSelection = F, seed = 3141) {
    
    if (class(RVM) != "RVineMatrix")
      stop("Object Not RVineMatrix!")
    
    
    if(missing(group) & missing(group.size))
    {
      group <- 1
      group.size <- 1
    } else if(!missing(group) & !missing(group.size))
    {
      # if(length(group) != length(group.size) )
      #   stop("Parameters group and group.size not equal length!")
      
      if(sum(group.size) != length(RVM$names))
        stop("Parameter group.size not well specifed as sum of group size not equal to number variables in RVineMatrix!")
    }
    
    if (missing(colours)) {
      colours <- colorspace::rainbow_hcl(length(group.size))
    } else {
      if (length(colours) != length(group.size)) {
        message(
          "Number of colours specified not equal to number of group size, using default colours\n")
        
        print(length(group.size))
        colours <- colorspace::rainbow_hcl(length(group.size))
        print(colours)
      }
    }
    
    sink(tempfile())
      rvineSummary <- summary(RVM)
    sink()
    
    # Deal with colour matching
    group_match <- unique(group) %>% sort(decreasing = T)
    matchedColor <- 
      cbind(group_match, key = seq(1:length(group_match))) %>%
      as_data_frame() %>% 
      left_join(.,
        cbind(key = seq(1:length(group_match)), colours) %>% as_data_frame(), 
        by = "key") %>% 
      left_join(group %>% as_data_frame(),., by = c("value" = "group_match"))
    
    
    if (length(shape) != length(group.size) | length(shape) == 1) {
      shape  <- rep(shape, sum(group.size))
    } else {
      shape <- rep(shape, group.size)
    }
    
    
    tau <-
      rvineSummary$tau[nrow(rvineSummary$tau), -ncol(rvineSummary$tau)]
    
    nodes <-
      data.frame(
        id = rvineSummary$names,
        title = rvineSummary$names,
        shape = shape,
        size = 15,
        color = matchedColor$colours,
        group = group
      )
    
    from <- diag(RVM$Matrix)[-length(diag(RVM$Matrix))]
    to <- c(tail(RVM$Matrix, 1))[-length(tail(RVM$Matrix, 1))]
    
    
    edges <-
      data.frame(
        from = rvineSummary$names[from],
        to = rvineSummary$names[to],
        value = 3,
        label = round(tau, 2)
      )
    
    if (length(group) != 1)
    {
      x  <- visNetwork(nodes, edges, height = "100%", width = "100%") %>%
        visLegend(
          useGroups = FALSE,
          addNodes = data.frame(
            label = group_match,
            shape = "circle",
            color = colours, 
            clickToUse = T
          )
        ) %>%
        visOptions(highlightNearest = TRUE, nodesIdSelection = nodesIdSelection) %>%
        visLayout(randomSeed = seed)
    } else {
      x  <- visNetwork(nodes, edges, height = "500px", width = "100%", zoom = 3) %>%
        visOptions(highlightNearest = TRUE, nodesIdSelection = nodesIdSelection) %>%
        visLayout(randomSeed = seed)
    }
    x
    # Save to html
    
    # visSave(x, file = "network.html")
    
  }

```


```{r, data_wrangling, include = F}
RVM <- readRDS("data/RVM.rds")

Market_info <- read.csv("data/Market_info.csv", stringsAsFactors = F)
Market_info <- 
  Market_info %>% mutate(Year1_Move = cut(X1.Year..Move,
                                       c("-Inf", 
                                          quantile(X1.Year..Move), 
                                          "Inf"),
                                       labels = c("Worst", "Negative", "Average", "Pos ret", "High ret", "Best")),
                       Year5_Move = cut(X5.year..Move,
                                       c("-Inf", 
                                          quantile(X5.year..Move), 
                                          "Inf"),
                                       labels = c("Worst", "Negative", "Average", "Pos ret", "High ret", "Best")),
                       MCapBillion = cut(Market.Cap/1e+09,
                                       c("-Inf", 
                                          quantile(Market.Cap)/1e+09, 
                                          "Inf")
                                       ))
shape  <- c("square",
  "triangle",
  "box",
  "circle",
  "dot",
  "star",
  "ellipse",
  "database",
  "text",
  "diamond"
  )

```

Vine Visualizations {data-icon="fa-tree"}
============================================================

Column {.sidebar data-width=300}
-----------------------------------------------------------------------
### ABOUT
__About Vines:__
A vine is a graphical tool for labeling constraints in high-dimensional probability distributions. In finance, vine copulas have been shown to effectively model tail risk in portfolio optimization applications as well as discover complex dependence structures. More information can be found [here](http://www.statistics.ma.tum.de/en/research/vine-copula-models/)
```{r}
selectInput('group', 'Generate Grouping', c("Market Cap", "Industry", "1 Year Performance","5 Year Performance"))

selectInput('group2', 'Generate Grouping2', c("Market Cap", "Industry", "1 Year Performance","5 Year Performance"))

selectInput('shape', 'Choose shape', shape)

numericInput('seed', 'Random formation seed', 3, 
              min = 1, max = 999)

shape  <- c(
  "square",
  "triangle",
  "box",
  "circle",
  "dot",
  "star",
  "ellipse",
  "database",
  "text",
  "diamond"
  )
```


```{r}
require(visNetwork, quietly = TRUE)

# First Vine

params <- reactive({
    if (input$group == "Market Cap")
    {
        group <- Market_info$MCapBillion %>% as.character()
        group.size <-  
          Market_info %>% 
          group_by(MCapBillion) %>%
          summarise(n = n()) %>% 
          select(n) %>% unlist
        colours <- c("#39c9bb", 	"#398fc9", 	"#39c973","#c93947", "#bb39c9")
        
        list(group, group.size, colours)
    } else if (input$group == "Industry"){
        group <- Market_info$Hanjo.Industry %>% as.character()
        group.size <-  
          Market_info %>% 
          group_by(Hanjo.Industry) %>%
          summarise(n = n()) %>% 
          select(n) %>% unlist 
        colours <- c("#39c9bb", "#398fc9", "#39c973"," #bb39c9", 	"#c9bb39")
        
        list(group, group.size, colours)
    } else if (input$group == "1 Year Performance"){
        group <- Market_info$Year1_Move %>% as.character()
        group.size <-  
          Market_info %>% 
          group_by(Year1_Move) %>%
          summarise(n = n()) %>% 
          select(n) %>% unlist 
        colours <- c("#39c9bb", 	"#398fc9", 	"#39c973")
        
        list(group, group.size, colours)
    } else if (input$group == "5 Year Performance"){
        group <- Market_info$Year5_Move %>% as.character()
        group.size <-  
          Market_info %>% 
          group_by(Year5_Move) %>%
          summarise(n = n()) %>% 
          select(n) %>% unlist 
        colours <- c("#39c9bb", 	"#398fc9", 	"#39c973")
        
        list(group, group.size, colours)
    }
  })



params2 <- reactive({
    if (input$group2 == "Market Cap")
    {
        group <- Market_info$MCapBillion %>% as.character()
        group.size <-  
          Market_info %>% 
          group_by(MCapBillion) %>%
          summarise(n = n()) %>% 
          select(n) %>% unlist
        colours <- c("#39c9bb", 	"#398fc9", 	"#39c973","#c93947", "#bb39c9")
        
        list(group, group.size, colours)
    } else if (input$group2 == "Industry"){
        group <- Market_info$Hanjo.Industry %>% as.character()
        group.size <-  
          Market_info %>% 
          group_by(Hanjo.Industry) %>%
          summarise(n = n()) %>% 
          select(n) %>% unlist 
        colours <- c("#ff4040",	"#ffa040", "#ff40a0", "#40ffff", "#4040ff", "#40ff40")
        
        list(group, group.size, colours)
    } else if (input$group2 == "1 Year Performance"){
        group <- Market_info$Year1_Move %>% as.character()
        group.size <-  
          Market_info %>% 
          group_by(Year1_Move) %>%
          summarise(n = n()) %>% 
          select(n) %>% unlist 
        colours <- c("#39c9bb", 	"#398fc9", 	"#39c973")
        
        list(group, group.size, colours)
    } else if (input$group2 == "5 Year Performance"){
        group <- Market_info$Year5_Move %>% as.character()
        group.size <-  
          Market_info %>% 
          group_by(Year5_Move) %>%
          summarise(n = n()) %>% 
          select(n) %>% unlist 
        colours <- c("#39c9bb", 	"#398fc9", 	"#39c973")
        
        list(group, group.size, colours)
    }
  })

```

Column {data-width=650}
-----------------------------------------------------------------------
```{r}
#Add copula type in Viz
        renderVisNetwork({
            VisVineR(
              RVM,
              group = params()[[1]],
              group.size = params()[[2]],
              seed = input$seed, 
              colours = params()[[3]],
              shape = input$shape
              )
            })

```

Column {data-width=650}
-----------------------------------------------------------------------
```{r}
#Add copula type in Viz
renderVisNetwork({
  VisVineR(
    RVM,
    group = params2()[[1]],
    group.size = params2()[[2]],
    colours = params2()[[3]],
    seed = input$seed, 
    shape = input$shape
    )
  })

```


Underlying data {data-icon="fa-database"}
============================================================
```{r}
datatable(Market_info, options = list(pageLength = 10))
```


